### ISSUE TITLE
Get formula

### ISSUE THREAD

**Issue by RedStone45789** [molshape/ChemFormula#13]
I am currently building a discord bot that can tell you the formula of a chemical by CAS number, can someone help me?

**Comment by molshape** [comment]
You cannot infer the chemical formula from a CAS Registry Number. In order to obtain the chemical formula behind a CAS number by entering it, a database query must be made. CAS offers its own API for this purpose: [CAS API](https://www.cas.org/solutions/cas-custom-services/workflow-integration/api), but their database is not freely accessible. There are other webservices that allow CAS RN search like [ChemSrc](https://www.chemsrc.com/en/), but I think that they don't offer a freely accessible API either.
